"""Cross-office reference suggestions from 'where to secure' text (suggestions only)."""

from pathlib import Path

import pytest

from citizengraph.parsing.crossoffice import (
    build_cross_office_doc,
    find_office_mentions,
    find_references,
)
from citizengraph.parsing.splitter import split_workbook

RAW = Path(__file__).resolve().parents[1] / "data" / "raw"


def offices(text: str) -> list[str]:
    return [o for o, _ in find_office_mentions(text)]


@pytest.mark.parametrize(
    "text",
    [
        "BPLO",
        "One Stop Shop of the BPLO",
        "Business Permits and Licensing Office (BPLO)",
        "Business Permits & Licensing Office (main office)",
        "business permits and licensing office",
    ],
)
def test_bplo_aliases(text):
    assert offices(text) == ["BPLO"]


@pytest.mark.parametrize("text", ["City Health Office (CHO)", "City Health Office", "CHO", "cho"])
def test_cho_aliases(text):
    assert offices(text) == (["CHO"] if text != "cho" else [])  # acronyms are case-sensitive


@pytest.mark.parametrize(
    "text",
    [
        "CSWDO",
        "City Social Welfare Development Office",
        "City Social Welfare and Development Office",
    ],
)
def test_cswdo_aliases(text):
    assert offices(text) == ["CSWDO"]


@pytest.mark.parametrize(
    "text",
    [
        "Civil Registry Office / or Notary Public",
        "Civil Registry Office - Civil Registrar",
        "PSA/LCR Calbayog thru BREQS PSA or LCR Office",
        "Philippine Statistics Authority / LCR Calbayog thru BREQS",
        "LCRO",
        "CCRO",
        "City Civil Registrar",
    ],
)
def test_civil_registry_aliases(text):
    assert offices(text) == ["LCRO"]


@pytest.mark.parametrize(
    "text",
    [
        "City Treasurer’s Office",
        "Barangay or City Treasurer’s Office",
        "Bureau of Fire Protection (BFP)",
        "City Planning and Development Office (CPDO)",
        "City Assessor's Office",
        "Brgy Hall",
        "Philippine National Police",
        "Department of Trade and Industry (DTI)",
        "Philippine Statistics Authority",
        "N/A",
        "",
    ],
)
def test_offices_outside_the_four_are_not_matched(text):
    assert offices(text) == []


def test_two_offices_in_one_text_and_one_hit_per_office():
    assert offices("City Health Office / BPLO / CHO") == ["CHO", "BPLO"]  # order of appearance


def test_matched_alias_is_reported():
    assert find_office_mentions("One Stop Shop of the BPLO") == [("BPLO", "BPLO")]
    assert find_office_mentions("Civil Registry Office / or Notary Public") == [
        ("LCRO", "Civil Registry")
    ]


@pytest.fixture(scope="module")
def drafts():
    out = []
    for name in ("BPLO-CC", "LCRO-CC", "CYPCC_HEALTH", "CYPCC_SOCIALWELFARE"):
        out += split_workbook(RAW / f"{name}.xlsx")
    return out


def test_real_cross_office_suggestions(drafts):
    cross = [r for r in find_references(drafts) if not r.same_office]
    got = {(r.from_id, r.key, r.target_office) for r in cross}
    assert got == {
        ("BPLO-01", "7", "CHO"),  # Sanitary Permit to Operate @ City Health Office (CHO)
        ("BPLO-02", "5", "CHO"),  # Medical Certificate @ City Health Office
        ("CSWDO-01", "3", "BPLO"),  # certification from BPLO of no existing business
    }


def test_offices_out_of_scope_produce_no_suggestion(drafts):
    refs = find_references(drafts)
    texts = {r.where_text for r in refs}
    assert not any("Fire Protection" in t or "Planning and Development" in t for t in texts)
    assert not any("Assessor" in t or "Treasurer" in t for t in texts)
    assert not [r for r in refs if r.from_id.startswith("CHO")]  # CHO checklists are N/A or PNP


def test_same_office_references_are_kept_separate(drafts):
    same = {(r.from_id, r.key) for r in find_references(drafts) if r.same_office}
    assert ("BPLO-01", "8") in same  # Employee's Occupational Permit @ BPLO
    assert ("BPLO-01", "1") in same
    assert ("LCRO-03", "1") in same
    assert all(not r.same_office for r in find_references(drafts) if r.from_id == "CSWDO-01")


def test_shared_merged_cell_is_noted(drafts):
    refs = {(r.from_id, r.key): r for r in find_references(drafts)}
    assert refs[("LCRO-03", "2")].shared_cell  # Birth Certificate shares the CENOMAR cell


def test_doc_is_deterministic_labelled_as_suggestions_and_creates_no_links(drafts):
    text = build_cross_office_doc(drafts)
    assert text == build_cross_office_doc(drafts)
    assert "suggest" in text.lower()
    assert "No graph link" in text
    assert "generated by `python -m citizengraph.parsing`" in text.lower()
    assert "| BPLO-01 |" in text and "| CSWDO-01 |" in text
    assert "## Across offices" in text and "## Within the same office" in text
    assert "Fire Protection" not in text


def test_doc_lists_each_cross_office_row_once(drafts):
    text = build_cross_office_doc(drafts)
    cross = [r for r in find_references(drafts) if not r.same_office]
    section = text.split("## Across offices")[1].split("## Within the same office")[0]
    assert section.count("\n| ") - 1 == len(cross)  # minus the header row
