// Constraints and indexes. Run once against an empty database.
CREATE CONSTRAINT office_id IF NOT EXISTS FOR (n:Office) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT service_id IF NOT EXISTS FOR (n:Service) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT requirement_id IF NOT EXISTS FOR (n:Requirement) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT agency_id IF NOT EXISTS FOR (n:Agency) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT step_id IF NOT EXISTS FOR (n:Step) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT role_id IF NOT EXISTS FOR (n:Role) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT fee_id IF NOT EXISTS FOR (n:Fee) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT variant_id IF NOT EXISTS FOR (n:Variant) REQUIRE n.id IS UNIQUE;
CREATE INDEX alias_text IF NOT EXISTS FOR (n:Alias) ON (n.text);
