"""Split a charter workbook into rough per-service drafts.

The source sheets are human-formatted documents, not tables. This module only *locates* the
pieces of each service block (metadata, requirements, steps, stated total) and runs the pure
parsers on the duration and fee cells. It does not curate, correct or infer anything: the output
under ``graph/seed/draft/`` is a starting point for hand-curation (docs/charter_data.md).

Block anchors are the header cells (``CHECKLIST OF REQUIREMENTS``, ``CITIZEN STEPS`` /
``CLIENT STEPS``, ``TOTAL``), not row numbers, and the requirement and step columns are read from
those header rows, so a new office's workbook is data, not code. Two layouts are known:

* BPLO / LCRO: a ``Name of frontline service:`` row, values in column B, steps in columns A to E.
* CHO / CSWDO: the service name is the ``N. Title`` row, metadata values start in column D
  (``Office/Section`` or ``Office or Department``), and the step columns sit at C, F, H, J (CHO)
  or C, F, G, I (CSWDO).

Merged cells
------------
A cell merged over several rows holds its value in the top-left cell only. For summable fields
(fees, processing time) the value stays on the top-left step and the other rows are marked
``*_shared_from`` so nothing is counted twice; this matches the charters' own totals (e.g. the
Occupational Permit's shared "2 minutes"). For non-summable fields (person responsible, where to
secure) the merged value is copied to every row and flagged.

Wrapped and split rows
----------------------
The CSWDO sheet wraps one cell's text over several rows (no merge). A row with no fee cell and no
time cell that follows a step is treated as a continuation of that step: its text is appended to
the same columns and the row is flagged ``orphan_row_glued``. Where the step's agency action is a
bullet list, the extra text becomes its own list item. A step whose label and person sit on one
row and whose fee and time sit on the next (CHO Laboratory Services) is *not* merged; it is
flagged ``possible_split_step``. Bullet points inside an agency-action cell are also exposed as
``agency_action_items`` (the raw text is kept).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from itertools import pairwise
from pathlib import Path
from typing import Any

import openpyxl
import yaml
from openpyxl.worksheet.worksheet import Worksheet

from citizengraph.parsing.durations import Duration, parse_duration
from citizengraph.parsing.fees import NO_CURRENCY_NOTE, FeeParse, parse_fees

# A printed list marker: "A.", "2.", "6.1", "6.1.", "F.3." (a bare "A " is a word, not a marker).
_MARKER = r"(?:[A-Za-z]|\d+)(?:\.\d+)+\.?|(?:[A-Za-z]|\d+)\."
_LABELLED = re.compile(rf"^(?P<label>{_MARKER})\s+(?P<rest>.*)$", re.DOTALL)
_WHERE_MARKER = re.compile(rf"^(?:{_MARKER})\s+")
_TITLE = re.compile(r"^\s*(?P<num>\d+)\.\s*(?P<rest>.*)$", re.DOTALL)
_NOT_STATED = re.compile(r"^[\s\-–—]*$")
_BULLET = re.compile(r"^\s*[•●▪\-*]\s+")
_LIST_BULLET = re.compile(r"^[•●▪◦·]\s*")  # agency-action lists; "-" is not a bullet there
_NA = re.compile(r"^n\s*/\s*a$", re.IGNORECASE)
_TOTAL_LABEL = re.compile(r"^total:?$", re.IGNORECASE)
_STEP_HEADERS = ("citizen steps", "client steps")
_TERMINAL = (".", ":", ";", ")", "?", "!")

_META_LABELS = {
    "name of frontline service": "name",
    "office or department": "office",
    "office/section": "office",
    "classification": "classification",
    "type of transaction": "transaction_type",
    "who may avail": "who_may_avail",
}

# Workbooks whose file name does not start with the office code.
FILE_OFFICE_CODES = {"CYPCC_HEALTH": "CHO", "CYPCC_SOCIALWELFARE": "CSWDO"}

DRAFT_HEADER = (
    "# DRAFT generated by `python -m citizengraph.parsing` from data/raw. Not the source of\n"
    "# truth: hand-curate into graph/seed/*.yaml. Do not hand-edit this file; re-generate instead.\n"
)


# --------------------------------------------------------------------------- data model


@dataclass
class Requirement:
    ref: int  # 1-based order within the service
    key: str | None  # "A", "6.1", ... as printed; None if unlabelled
    kind: str  # item | group | bullet
    text: str
    where_to_secure: str | None
    parent_ref: int | None
    where_shared_with: int | None  # ref of the requirement whose merged cell this value came from
    source_row: int

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            "ref": self.ref,
            "key": self.key,
            "kind": self.kind,
            "text": self.text,
            "where_to_secure": self.where_to_secure,
            "parent_ref": self.parent_ref,
        }
        if self.where_shared_with is not None:
            d["where_shared_with"] = self.where_shared_with
        d["source_row"] = self.source_row
        return d


@dataclass
class Step:
    order: int
    label: str | None  # "1.1.", "F.3." ... as printed on the agency action
    citizen_step_group: int
    citizen_action: str | None  # only on the first row of a group
    agency_action: str | None
    fees: FeeParse
    time: Duration
    person_responsible_raw: str | None  # staff names live here only; never citizen-facing
    source_row: int
    fees_span: int = 1
    time_span: int = 1
    fees_shared_from: int | None = None  # order of the step whose merged cell holds the value
    time_shared_from: int | None = None
    agency_action_items: list[str] | None = None  # only when the cell has bullet points

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            "order": self.order,
            "label": self.label,
            "citizen_step_group": self.citizen_step_group,
            "citizen_action": self.citizen_action,
            "agency_action": self.agency_action,
        }
        if self.agency_action_items is not None:
            d["agency_action_items"] = self.agency_action_items
        d.update(
            {
                "fees": self.fees.to_dict(),
                "time": self.time.to_dict(),
                "person_responsible_raw": self.person_responsible_raw,
                "source_row": self.source_row,
            }
        )
        for name in ("fees_span", "time_span"):
            if getattr(self, name) > 1:
                d[name] = getattr(self, name)
        for name in ("fees_shared_from", "time_shared_from"):
            if getattr(self, name) is not None:
                d[name] = getattr(self, name)
        return d


@dataclass
class StatedTotal:
    fee_text: str | None
    time_text: str | None
    fee: FeeParse
    time: Duration
    source_row: int | None

    def to_dict(self) -> dict[str, Any]:
        return {
            "fee_text": self.fee_text,
            "time_text": self.time_text,
            "fee": self.fee.to_dict(),
            "time": self.time.to_dict(),
            "source_row": self.source_row,
        }


@dataclass
class ServiceDraft:
    draft_id: str
    source_file: str
    source_sheet: str
    source_number: int
    source_rows: tuple[int, int]
    title: str | None
    description: str | None
    name: str | None
    office: str | None
    classification: str | None
    classification_raw: str | None
    transaction_type: str | None
    who_may_avail: str | None
    requirements: list[Requirement] = field(default_factory=list)
    steps: list[Step] = field(default_factory=list)
    total: StatedTotal | None = None
    flags: list[dict[str, str]] = field(default_factory=list)

    def flat_fees(self) -> list[dict[str, Any]]:
        out = []
        for step in self.steps:
            for item in step.fees.items:
                out.append({"step": step.order, **item.to_dict()})
        return out

    def to_dict(self) -> dict[str, Any]:
        return {
            "draft_id": self.draft_id,
            "source": {
                "file": self.source_file,
                "sheet": self.source_sheet,
                "number": self.source_number,
                "rows": list(self.source_rows),
            },
            "title": self.title,
            "description": self.description,
            "name": self.name,
            "office": self.office,
            "classification": self.classification,
            "classification_raw": self.classification_raw,
            "transaction_type": self.transaction_type,
            "who_may_avail": self.who_may_avail,
            "requirements": [r.to_dict() for r in self.requirements],
            "steps": [s.to_dict() for s in self.steps],
            "fees": self.flat_fees(),
            "total": self.total.to_dict() if self.total else None,
            "flags": self.flags,
        }


# --------------------------------------------------------------------------- cell helpers


def _clean(value: object) -> str | None:
    """Text of a cell with trailing spaces removed per line; None when empty."""
    if value is None:
        return None
    text = str(value).replace("\r", "").replace("\xa0", " ")
    lines = [re.sub(r"[ \t]+", " ", ln).strip() for ln in text.split("\n")]
    text = "\n".join(lines).strip()
    return text or None


class _Sheet:
    """Merged-cell aware access to a worksheet."""

    def __init__(self, ws: Worksheet) -> None:
        self.ws = ws
        self.max_row = ws.max_row
        self.max_col = ws.max_column
        self._merge: dict[tuple[int, int], tuple[int, int, int]] = {}
        for rng in ws.merged_cells.ranges:
            for r in range(rng.min_row, rng.max_row + 1):
                for c in range(rng.min_col, rng.max_col + 1):
                    self._merge[(r, c)] = (rng.min_row, rng.min_col, rng.max_row - rng.min_row + 1)

    def own(self, row: int, col: int) -> str | None:
        """Value written in the cell itself (None for the non-top-left cells of a merge)."""
        return _clean(self.ws.cell(row, col).value)

    def merged(self, row: int, col: int) -> tuple[str | None, int | None, int]:
        """(value, top-left row if this cell is a non-top-left merged cell else None, span rows)."""
        origin = self._merge.get((row, col))
        if origin is None:
            return self.own(row, col), None, 1
        top_row, top_col, span = origin
        value = _clean(self.ws.cell(top_row, top_col).value)
        if top_row == row and top_col == col:
            return value, None, span
        return value, top_row, span

    def row_text(self, row: int) -> str:
        return " ".join(t for c in range(1, 6) if (t := self.own(row, c)) is not None)


def _norm_label(text: str | None) -> str:
    return (text or "").strip().rstrip(":").strip().lower()


def _join(first: str | None, second: str | None, sep: str) -> str | None:
    if first is None or first == "":
        return second
    if second is None or second == "":
        return first
    return f"{first}{sep}{second}"


# --------------------------------------------------------------------------- block parsing


@dataclass(frozen=True)
class _Cols:
    """Column numbers of the steps table, read from its header row."""

    client: int = 1
    agency: int = 2
    fees: int = 3
    time: int = 4
    person: int = 5


def _step_columns(sh: _Sheet, row: int) -> _Cols:
    found: dict[str, int] = {}
    for col in range(1, sh.max_col + 1):
        text = _norm_label(sh.own(row, col))
        if not text:
            continue
        if text in _STEP_HEADERS:
            found["client"] = col
        elif text.startswith("agency action"):
            found["agency"] = col
        elif text.startswith("fees"):
            found["fees"] = col
        elif text.startswith("processing time"):
            found["time"] = col
        elif text.startswith("person responsible"):
            found["person"] = col
    missing = {"client", "agency", "fees", "time", "person"} - set(found)
    if missing:
        raise ValueError(f"steps header at row {row} lacks columns: {sorted(missing)}")
    return _Cols(**found)


def _where_column(sh: _Sheet, row: int) -> int:
    for col in range(2, sh.max_col + 1):
        if _norm_label(sh.own(row, col)).startswith("where to secure"):
            return col
    return 3


def _find_row(sh: _Sheet, start: int, stop: int, predicate) -> int | None:
    for r in range(start, stop + 1):
        text = sh.own(r, 1)
        if text is not None and predicate(text):
            return r
    return None


def _find_blocks(sh: _Sheet) -> list[tuple[int, int, int]]:
    """(title_row, first metadata row, checklist header row) for every service block."""
    blocks = []
    for checklist in range(1, sh.max_row + 1):
        if not _norm_label(sh.own(checklist, 1)).startswith("checklist of requirement"):
            continue
        meta_start = checklist
        r = checklist - 1
        while r >= 1:
            text = sh.own(r, 1)
            if text is None:
                r -= 1
            elif _norm_label(text) in _META_LABELS:
                meta_start = r
                r -= 1
            else:
                break
        blocks.append((_parse_title(sh, meta_start)[3], meta_start, checklist))
    return blocks


def _meta_value(sh: _Sheet, row: int) -> str | None:
    for col in range(2, sh.max_col + 1):
        value = sh.own(row, col)
        if value is not None:
            return value
    return None


def _parse_title(sh: _Sheet, name_row: int) -> tuple[int | None, str | None, str | None, int]:
    """Walk back over up to three non-empty rows to the ``N. Title`` row above the description."""
    rows = []
    r = name_row - 1
    while r >= 1 and len(rows) < 3:
        text = sh.own(r, 1)
        if text is not None:
            rows.append((r, text))
        r -= 1
    for idx, (row, text) in enumerate(rows):
        m = _TITLE.match(text)
        if m:
            desc_rows = [t for _, t in reversed(rows[:idx])]
            return int(m.group("num")), text, "\n".join(desc_rows) or None, row
    return None, None, None, name_row


def _parse_requirements(
    sh: _Sheet, start: int, stop: int, where_col: int
) -> tuple[list[Requirement], list[dict]]:
    reqs: list[Requirement] = []
    flags: list[dict[str, str]] = []
    by_key: dict[str, int] = {}
    current_group: int | None = None
    ref_by_row: dict[int, int] = {}
    last_row = 0
    saw_na = False

    for row in range(start, stop + 1):
        text = sh.own(row, 1)
        where_raw, shared_row, _ = sh.merged(row, where_col)
        if text is None:
            if where_raw is not None and shared_row is None:
                flags.append(
                    {"code": "orphan_where_to_secure", "message": f"row {row}: {where_raw!r}"}
                )
            continue
        if _NA.match(text):  # "N/A" checklist: no requirements, not a requirement called N/A
            saw_na = True
            continue

        kind = "item"
        key: str | None = None
        parent_ref: int | None = None
        if _BULLET.match(text):
            kind = "bullet"
            text = _BULLET.sub("", text).strip()
            parent_ref = current_group
        else:
            m = _LABELLED.match(text)
            if m:
                key, text = m.group("label").rstrip("."), m.group("rest").strip()
            if text.endswith(":") and "\n" not in text:
                kind = "group"
                current_group = len(reqs) + 1
            else:
                current_group = None
                if key and "." in key:
                    parent_ref = by_key.get(key.rsplit(".", 1)[0])

        prev = reqs[-1] if reqs else None
        if (
            prev is not None
            and kind == "item"
            and key is None
            and where_raw is None
            and prev.kind == "item"
            and prev.key is not None
            and row == last_row + 1
            and not prev.text.rstrip().endswith(_TERMINAL)
        ):  # a labelled requirement whose text wrapped onto the next row
            prev.text = f"{prev.text} {text}"
            ref_by_row[row] = prev.ref
            last_row = row
            flags.append(
                {
                    "code": "requirement_fragment_glued",
                    "message": f"row {row} continues requirement {prev.key} (row {prev.source_row})",
                }
            )
            continue

        where = None
        where_na = False
        where_shared_with = None
        if where_raw is not None and _NA.match(where_raw):
            where_na = True
        elif where_raw is not None and not _NOT_STATED.match(where_raw):
            where = _WHERE_MARKER.sub("", where_raw, count=1).strip() or None
            if shared_row is not None:
                where_shared_with = ref_by_row.get(shared_row)
                flags.append(
                    {
                        "code": "where_to_secure_shared",
                        "message": f"row {row} shares a merged 'where to secure' cell "
                        f"with row {shared_row}: {where!r}",
                    }
                )

        ref = len(reqs) + 1
        ref_by_row[row] = ref
        last_row = row
        if key and key not in by_key:
            by_key[key] = ref
        reqs.append(Requirement(ref, key, kind, text, where, parent_ref, where_shared_with, row))
        if kind != "group" and where is None:
            code = "where_to_secure_na" if where_na else "where_to_secure_missing"
            flags.append({"code": code, "message": f"requirement {key or ref}: {text[:60]!r}"})
    if saw_na and not reqs:
        flags.append({"code": "no_requirements_listed", "message": "checklist says N/A"})
    return reqs, flags


def _split_bullets(text: str | None) -> list[str] | None:
    """Items of a bullet list inside one cell; None when the cell has no bullet points.

    A line starting with a bullet begins an item; a following line without a bullet is a wrapped
    continuation of it; a blank line ends the item.
    """
    if text is None:
        return None
    lines = [ln.strip() for ln in text.split("\n")]
    if not any(_LIST_BULLET.match(ln) for ln in lines):
        return None
    items: list[str] = []
    current: int | None = None
    for line in lines:
        if not line:
            current = None
            continue
        m = _LIST_BULLET.match(line)
        if m:
            item = line[m.end() :].strip()
            if item:
                items.append(item)
                current = len(items) - 1
            else:
                current = None
        elif current is None:
            items.append(line)
            current = len(items) - 1
        else:
            items[current] = f"{items[current]} {line}"
    return items


def _parse_steps(
    sh: _Sheet, start: int, stop: int, cols: _Cols
) -> tuple[list[Step], list[dict[str, str]]]:
    steps: list[Step] = []
    flags: list[dict[str, str]] = []
    group = 0
    order_by_row: dict[int, int] = {}

    for row in range(start, stop + 1):
        citizen = sh.own(row, cols.client)
        agency = sh.own(row, cols.agency)
        fees_val, fees_top, fees_span = sh.merged(row, cols.fees)
        time_val, time_top, time_span = sh.merged(row, cols.time)
        person_val, _person_top, _ = sh.merged(row, cols.person)
        if all(v is None for v in (citizen, agency, fees_val, time_val, person_val)):
            continue

        if steps and fees_val is None and time_val is None:
            # No fee and no time: a wrapped continuation of the step above (CSWDO layout).
            prev = steps[-1]
            prev.citizen_action = _join(prev.citizen_action, citizen, " ")
            if agency is not None:
                sep = "\n\n" if _split_bullets(prev.agency_action) is not None else " "
                prev.agency_action = _join(prev.agency_action, agency, sep)
            if person_val is not None and not _NOT_STATED.match(person_val):
                prev.person_responsible_raw = _join(prev.person_responsible_raw, person_val, " ")
            flags.append(
                {
                    "code": "orphan_row_glued",
                    "message": f"row {row} has no fee or time; its text was appended to "
                    f"step {prev.order}",
                }
            )
            continue

        if citizen is not None or group == 0:
            group += 1

        label = None
        if agency:
            m = _LABELLED.match(agency)
            if m:
                label, agency = m.group("label"), m.group("rest").strip()

        order = len(steps) + 1
        order_by_row[row] = order
        step = Step(
            order=order,
            label=label,
            citizen_step_group=group,
            citizen_action=citizen,
            agency_action=agency,
            fees=parse_fees(None if fees_top else fees_val),
            time=parse_duration(None if time_top else time_val),
            person_responsible_raw=None
            if person_val is None or _NOT_STATED.match(person_val)
            else person_val,
            source_row=row,
            fees_span=fees_span if not fees_top else 1,
            time_span=time_span if not time_top else 1,
            fees_shared_from=order_by_row.get(fees_top) if fees_top else None,
            time_shared_from=order_by_row.get(time_top) if time_top else None,
        )
        steps.append(step)
        where = f"step {order} (row {row})"
        if step.time.status == "unparsed":
            flags.append({"code": "time_unparsed", "message": f"{where}: {step.time.raw!r}"})
        elif step.time.status == "ambiguous":
            flags.append(
                {
                    "code": "time_ambiguous",
                    "message": f"{where}: {step.time.raw!r} kept raw; {step.time.review}",
                }
            )
        elif step.time.status == "not_stated" and time_top is None:
            flags.append({"code": "time_not_stated", "message": f"{where}"})
        if step.time.normalizations:
            flags.append(
                {
                    "code": "time_typo_normalized",
                    "message": f"{where}: {step.time.raw!r} read as {list(step.time.normalizations)}",
                }
            )
        if step.fees.status == "text_only":
            flags.append({"code": "fee_text_only", "message": f"{where}: {step.fees.notes}"})
        if any(i.note == NO_CURRENCY_NOTE for i in step.fees.items):
            flags.append(
                {
                    "code": "fee_no_currency_sign",
                    "message": f"{where}: {step.fees.raw!r} has no peso sign; read as an amount",
                }
            )
        if step.person_responsible_raw is None:
            flags.append({"code": "person_missing", "message": f"{where}"})
        if fees_top is not None or time_top is not None:
            flags.append(
                {"code": "merged_cell_shared", "message": f"{where}: fees/time cell merged upward"}
            )

    for step in steps:
        step.agency_action_items = _split_bullets(step.agency_action)
    for step, nxt in pairwise(steps):
        if (
            step.fees.raw is None
            and step.time.raw is None
            and step.fees_shared_from is None
            and step.time_shared_from is None
            and (nxt.fees.raw is not None or nxt.time.raw is not None)
            and nxt.citizen_action is None
            and nxt.person_responsible_raw is None
        ):
            flags.append(
                {
                    "code": "possible_split_step",
                    "message": f"step {step.order} (row {step.source_row}) has no fee or time and "
                    f"step {nxt.order} (row {nxt.source_row}) has no label or person; they may be "
                    "one step. Kept as two.",
                }
            )
    return steps, flags


def _parse_total(sh: _Sheet, row: int | None, cols: _Cols) -> StatedTotal | None:
    if row is None:
        return None
    fee_text, time_text = sh.own(row, cols.fees), sh.own(row, cols.time)
    return StatedTotal(fee_text, time_text, parse_fees(fee_text), parse_duration(time_text), row)


def _find_total_row(sh: _Sheet, start: int, stop: int, cols: _Cols) -> int | None:
    """Row whose label cell (left of the fees column) reads TOTAL."""
    for r in range(start, stop + 1):
        for col in range(1, cols.fees):
            text = sh.own(r, col)
            if text is not None and _TOTAL_LABEL.match(text):
                return r
    return None


def _parse_block(
    sh: _Sheet,
    title_row: int,
    meta_start: int,
    checklist_row: int,
    block_stop: int,
    office_code: str,
    source_file: str,
    sheet: str,
) -> ServiceDraft:
    number, title, description, _ = _parse_title(sh, meta_start)

    meta: dict[str, str | None] = {}
    for r in range(meta_start, checklist_row):
        label = _norm_label(sh.own(r, 1))
        if label in _META_LABELS:
            meta[_META_LABELS[label]] = _meta_value(sh, r)

    where_col = _where_column(sh, checklist_row)
    steps_row = _find_row(sh, checklist_row, block_stop, lambda t: _norm_label(t) in _STEP_HEADERS)
    cols = _step_columns(sh, steps_row) if steps_row is not None else _Cols()
    total_row = _find_total_row(sh, steps_row or checklist_row, block_stop, cols)

    reqs, req_flags = _parse_requirements(
        sh, checklist_row + 1, (steps_row or checklist_row + 1) - 1, where_col
    )
    steps: list[Step] = []
    step_flags: list[dict[str, str]] = []
    if steps_row is not None:
        steps, step_flags = _parse_steps(sh, steps_row + 1, (total_row or block_stop + 1) - 1, cols)
    total = _parse_total(sh, total_row, cols)

    classification_raw = meta.get("classification")
    flags = req_flags + step_flags
    if meta.get("who_may_avail") is None:
        flags.append({"code": "who_may_avail_blank", "message": "left null"})
    if total is None:
        flags.append({"code": "total_missing", "message": "no TOTAL row found"})
    else:
        if total.time.status == "unparsed":
            flags.append({"code": "total_time_unparsed", "message": repr(total.time.raw)})
        if total.time.status == "ambiguous":
            flags.append(
                {
                    "code": "total_time_ambiguous",
                    "message": f"{total.time.raw!r} kept raw; {total.time.review}",
                }
            )
        if total.time.normalizations:
            flags.append(
                {
                    "code": "total_time_typo_normalized",
                    "message": f"{total.time.raw!r} read as {list(total.time.normalizations)}",
                }
            )
        if total.fee.status == "text_only":
            flags.append({"code": "total_fee_text_only", "message": repr(total.fee.raw)})
        if any(i.note == NO_CURRENCY_NOTE for i in total.fee.items):
            flags.append({"code": "total_fee_no_currency_sign", "message": repr(total.fee.raw)})

    name = meta.get("name")
    if "name" not in meta and title is not None:  # CHO / CSWDO: the title row names the service
        name = _TITLE.match(title).group("rest").strip() or None  # type: ignore[union-attr]

    return ServiceDraft(
        draft_id=f"{office_code}-{number:02d}"
        if number is not None
        else f"{office_code}-r{meta_start}",
        source_file=source_file,
        source_sheet=sheet,
        source_number=number if number is not None else 0,
        source_rows=(title_row, total_row or block_stop),
        title=title,
        description=description,
        name=name,
        office=meta.get("office"),
        classification=classification_raw.strip().upper() if classification_raw else None,
        classification_raw=classification_raw,
        transaction_type=meta.get("transaction_type"),
        who_may_avail=meta.get("who_may_avail"),
        requirements=reqs,
        steps=steps,
        total=total,
        flags=flags,
    )


def office_code_for(path: str | Path) -> str:
    """Office prefix of the draft ids, e.g. BPLO-CC.xlsx -> BPLO, CYPCC_HEALTH.xlsx -> CHO."""
    stem = Path(path).stem
    return FILE_OFFICE_CODES.get(stem.upper(), re.split(r"[-_]", stem)[0].upper())


def split_workbook(path: str | Path) -> list[ServiceDraft]:
    """Split every service block on the first sheet of a charter workbook."""
    path = Path(path)
    wb = openpyxl.load_workbook(path, read_only=False, data_only=True)
    try:
        ws = wb.worksheets[0]
        sh = _Sheet(ws)
        office_code = office_code_for(path)
        blocks = _find_blocks(sh)
        drafts = []
        for idx, (title_row, meta_start, checklist_row) in enumerate(blocks):
            stop = blocks[idx + 1][0] - 1 if idx + 1 < len(blocks) else sh.max_row
            drafts.append(
                _parse_block(
                    sh, title_row, meta_start, checklist_row, stop, office_code, path.name, ws.title
                )
            )
        return drafts
    finally:
        wb.close()


# --------------------------------------------------------------------------- YAML output


class _Dumper(yaml.SafeDumper):
    pass


def _str_representer(dumper: yaml.SafeDumper, data: str) -> yaml.ScalarNode:
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_Dumper.add_representer(str, _str_representer)


def dump_draft(draft: ServiceDraft) -> str:
    body = yaml.dump(
        draft.to_dict(),
        Dumper=_Dumper,
        sort_keys=False,
        allow_unicode=True,
        width=100,
        default_flow_style=False,
    )
    return DRAFT_HEADER + body


def write_drafts(drafts: list[ServiceDraft], out_dir: str | Path) -> list[Path]:
    """Write one ``<draft_id>.yaml`` per service. Output is deterministic (no timestamps)."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    paths = []
    for draft in drafts:
        path = out / f"{draft.draft_id}.yaml"
        path.write_text(dump_draft(draft), encoding="utf-8")
        paths.append(path)
    return paths
