// Generates src/design/tokens.css (CSS variables + Tailwind theme colours) from src/design/tokens.json.
import { writeFileSync } from "node:fs";
import tokens from "../src/design/tokens.json" with { type: "json" };
import { resolveTheme } from "../src/design/contrast.js";

const vars = (theme, indent) =>
  Object.entries(resolveTheme(tokens, theme))
    .map(([role, hex]) => `${indent}--${role}: ${hex};`)
    .join("\n");

const roles = Object.keys(tokens.themes.light);
const css = `/* GENERATED by scripts/gen-tokens.mjs from tokens.json. Do not edit by hand. */

/* Tailwind's default colours are removed on purpose: only our palette exists. */
@theme {
  --color-*: initial;
  --color-transparent: transparent;
  --color-current: currentColor;
}

:root {
  color-scheme: light;
${vars("light", "  ")}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${vars("dark", "    ")}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${vars("dark", "  ")}
}

@theme inline {
${roles.map((r) => `  --color-${r}: var(--${r});`).join("\n")}
}
`;
writeFileSync(new URL("../src/design/tokens.css", import.meta.url), css);
console.log(`tokens.css: ${roles.length} roles x ${Object.keys(tokens.themes).length} themes`);
